clang-tidy: remove unused fields
Clang-tidy flagged bus as unused private fields in PostCode.
Removed unused bus to fix below error

'''
./inc/post_code.hpp:187:23: error: private field 'bus' is not used [-Werror,-Wunused-private-field]
  187 |     sdbusplus::bus_t& bus;
'''

Change-Id: Iddf93bbcfb5d5e22efd1c2420b6fe2714513e659
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>